#[derive(Debug, PartialEq)]
pub enum Token {
    Identifier(String),
    Number(i32),
    Plus,
    Minus,
    Eof,
    WhiteSpace,
    BreakLine,
    Text(String),
    LeftParenthesis,
    RightParenthesis,
    Comma,  
    Equal,
    EqualEqual,
    EqualEqualEqual,
    Not,
    NotEqual,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    Arrow, // =>
    Illegal(String),
    Asterisk,
    Slash,
    Percent,
    Interpolation(String, String),
    Symbol(String),
    LeftBrace,
    RightBrace,
    Colon,
}